name: Build Pi Stream v2 Upsilon

on:
  push:
    branches: [ main, upsilon-dev ]
  pull_request:
    branches: [ main, upsilon-dev ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies and ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          python3 \
          python3-pip \
          pkg-config \
          libpng-dev \
          libpng16-16 \
          libpng-tools \
          libfreetype6-dev \
          libjpeg-dev \
          imagemagick
        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
        tar -xjf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
        sudo mv gcc-arm-none-eabi-10.3-2021.10 /opt/
        echo "/opt/gcc-arm-none-eabi-10.3-2021.10/bin" >> $GITHUB_PATH

    - name: Build Upsilon
      run: |
        make clean
        make OMEGA_USERNAME="PiStream" PLATFORM=device TARGET=n0110 binpack -j1

    - name: Create release artifacts
      run: |
        mkdir -p release
        if [ -d "output/release/device/bootloader" ]; then
          echo "✅ Build successful - copying binpack files"
          cp -r output/release/device/bootloader/* release/
          ls -la release/
        else
          echo "❌ Build failed - no bootloader directory generated"
          ls -la output/release/device/ || echo "No device directory"
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pistream-v2-upsilon
        path: release/
